#!/bin/bash

SCRIPT_PATH=$(realpath $0)
DIR_PATH=$(dirname $SCRIPT_PATH)
LIB_PATH=$DIR_PATH/lib
FILE_PATH=$(realpath $1)
S_PATH=${FILE_PATH%.lat}.s
O_PATH=${FILE_PATH%.lat}.o
BIN_PATH=${FILE_PATH%.lat}

./latte --O3 $FILE_PATH && nasm -f elf64 $S_PATH -o $O_PATH && gcc -no-pie $O_PATH $LIB_PATH/runtime.o -o $BIN_PATH