name:                latte-compiler
version:             0.1.0.0
github:              "aasfga/latte"
license:             BSD3
author:              "Dominik Grybos"
maintainer:          "dominik.grybos@gmail.com"
copyright:           "2020 Dominik Grybos"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aasfga/latte#readme>

build-tools:
  - alex
  - happy

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 6
- mtl
- filepath
- text
- containers
- transformers
- microlens-platform
- bimap

library:
  source-dirs: src

executables:
  latte:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latte-compiler
    - optparse-applicative

tests:
  latte-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latte-compiler
    - tasty
    - tasty-hunit
    - shelly