name:                latte
version:             0.1.0.0
github:              "aasfga/latte"
license:             BSD3
author:              "Dominik Grybos"
maintainer:          "dominik.grybos@gmail.com"
copyright:           "2020 Dominik Grybos"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aasfga/latte#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 6
- mtl
- containers
- microlens-platform
- tasty >= 1.4
- tasty-hunit

library:
  source-dirs: src

executables:
  latte-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latte

tests:
  latte-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - latte
    - tasty
    - tasty-hunit
